name: Automated Testing Pipeline

on:
  push:
    branches: [ master, main, develop, feature/*, fix/* ]
  pull_request:
    branches: [ master, main, develop ]
  workflow_dispatch: # 手動実行を可能にする
    inputs:
      test_level:
        description: 'Test level to run'
        required: false
        default: 'all'
        type: choice
        options:
        - 'lint'
        - 'unit'
        - 'integration' 
        - 'all'
      coverage_threshold:
        description: 'Minimum coverage percentage'
        required: false
        default: '80'
        type: string

jobs:
  lint:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install linting dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black mypy

    - name: Run Black formatter check
      run: |
        echo "🎨 Running Black formatter check..."
        black --check --diff src/ tests/ || (echo "❌ Black formatting issues found" && exit 1)

    - name: Run Flake8 linter
      run: |
        echo "🔍 Running Flake8 linter..."
        flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/ tests/ --count --max-complexity=10 --max-line-length=127 --statistics

    - name: Run MyPy type checking
      run: |
        echo "🔬 Running MyPy type checking..."
        mypy src/ || echo "⚠️ MyPy warnings found (continuing)"

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    if: always() && (needs.lint.result == 'success' || github.event.inputs.test_level == 'unit' || github.event.inputs.test_level == 'all')
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg mecab mecab-ipadic-utf8 libmecab-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov pytest-xdist pytest-mock

    - name: Run unit tests
      env:
        PYTEST_CURRENT_TEST: "true"
      run: |
        echo "🧪 Running unit tests with Python ${{ matrix.python-version }}..."
        python -m pytest tests/unit/ \
          -v \
          --tb=short \
          --cov=src \
          --cov-report=xml:coverage-${{ matrix.python-version }}.xml \
          --cov-report=html:htmlcov-${{ matrix.python-version }} \
          --cov-report=term-missing \
          --junit-xml=junit-${{ matrix.python-version }}.xml \
          -n auto

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports-${{ matrix.python-version }}
        path: |
          coverage-${{ matrix.python-version }}.xml
          htmlcov-${{ matrix.python-version }}/
          junit-${{ matrix.python-version }}.xml

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [lint, unit-tests]
    if: always() && ((needs.lint.result == 'success' && needs.unit-tests.result == 'success') || github.event.inputs.test_level == 'integration' || github.event.inputs.test_level == 'all')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg mecab mecab-ipadic-utf8 libmecab-dev fonts-noto-cjk

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov pytest-mock

    - name: Run integration tests
      env:
        # テスト用の環境変数（実際のAPIキーは使わない）
        GEMINI_API_KEY: "test-api-key"
        GOOGLE_AUTH_METHOD: "mock"
        PYTEST_CURRENT_TEST: "true"
        INTEGRATION_TEST_MODE: "true"
      timeout-minutes: 30
      run: |
        echo "🔗 Running integration tests..."
        python -m pytest tests/integration/ \
          -v \
          --tb=short \
          --cov=src \
          --cov-append \
          --cov-report=xml:integration-coverage.xml \
          --cov-report=html:integration-htmlcov \
          --junit-xml=integration-junit.xml

    - name: Upload integration test results
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-results
        path: |
          integration-coverage.xml
          integration-htmlcov/
          integration-junit.xml

  coverage-analysis:
    name: Coverage Analysis
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    if: always() && (needs.unit-tests.result == 'success' || needs.integration-tests.result == 'success')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download all coverage reports
      uses: actions/download-artifact@v4
      with:
        pattern: coverage-reports-*
        merge-multiple: true

    - name: Download integration coverage
      uses: actions/download-artifact@v4
      with:
        name: integration-test-results
        path: integration/

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install coverage tools
      run: |
        python -m pip install --upgrade pip
        pip install coverage[toml] pytest-cov

    - name: Combine coverage reports
      run: |
        echo "📊 Combining coverage reports..."
        coverage combine coverage-*.xml || echo "No unit test coverage files found"
        if [ -f "integration/integration-coverage.xml" ]; then
          coverage combine integration/integration-coverage.xml
        fi
        coverage report --show-missing
        coverage html -d combined-coverage
        coverage xml -o combined-coverage.xml

    - name: Check coverage threshold
      run: |
        THRESHOLD=${{ github.event.inputs.coverage_threshold || '80' }}
        echo "📋 Checking coverage threshold: ${THRESHOLD}%"
        COVERAGE=$(coverage report --format=total)
        echo "Current coverage: ${COVERAGE}%"
        if (( $(echo "$COVERAGE >= $THRESHOLD" | bc -l) )); then
          echo "✅ Coverage threshold met: ${COVERAGE}% >= ${THRESHOLD}%"
        else
          echo "❌ Coverage threshold not met: ${COVERAGE}% < ${THRESHOLD}%"
          echo "::error::Coverage ${COVERAGE}% is below threshold ${THRESHOLD}%"
          exit 1
        fi

    - name: Upload combined coverage
      uses: actions/upload-artifact@v4
      with:
        name: combined-coverage-report
        path: |
          combined-coverage/
          combined-coverage.xml

    - name: Comment coverage on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const coverage = fs.readFileSync('combined-coverage.xml', 'utf8');
          const coverageMatch = coverage.match(/line-rate="([0-9.]+)"/);
          const coveragePercent = coverageMatch ? Math.round(parseFloat(coverageMatch[1]) * 100) : 'Unknown';
          
          const comment = `## 📊 テストカバレッジレポート
          
          **カバレッジ**: ${coveragePercent}%
          **閾値**: ${{ github.event.inputs.coverage_threshold || '80' }}%
          **状態**: ${coveragePercent >= ${{ github.event.inputs.coverage_threshold || '80' }} ? '✅ 合格' : '❌ 不合格'}
          
          詳細なレポートは [Artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) からダウンロードできます。`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [lint, unit-tests, integration-tests, coverage-analysis]
    if: always()

    steps:
    - name: Generate test summary
      run: |
        echo "# 🧪 テスト実行サマリー" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## 実行結果" >> $GITHUB_STEP_SUMMARY
        echo "| ステージ | 結果 | 詳細 |" >> $GITHUB_STEP_SUMMARY
        echo "|----------|------|------|" >> $GITHUB_STEP_SUMMARY
        echo "| Lint | ${{ needs.lint.result == 'success' && '✅ 成功' || needs.lint.result == 'failure' && '❌ 失敗' || '⏭️ スキップ' }} | コード品質チェック |" >> $GITHUB_STEP_SUMMARY
        echo "| Unit Tests | ${{ needs.unit-tests.result == 'success' && '✅ 成功' || needs.unit-tests.result == 'failure' && '❌ 失敗' || '⏭️ スキップ' }} | 単体テスト（Python 3.9-3.11） |" >> $GITHUB_STEP_SUMMARY
        echo "| Integration Tests | ${{ needs.integration-tests.result == 'success' && '✅ 成功' || needs.integration-tests.result == 'failure' && '❌ 失敗' || '⏭️ スキップ' }} | 統合テスト |" >> $GITHUB_STEP_SUMMARY
        echo "| Coverage Analysis | ${{ needs.coverage-analysis.result == 'success' && '✅ 成功' || needs.coverage-analysis.result == 'failure' && '❌ 失敗' || '⏭️ スキップ' }} | カバレッジ分析 |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [[ "${{ needs.lint.result }}" == "success" && "${{ needs.unit-tests.result }}" == "success" && "${{ needs.integration-tests.result }}" == "success" && "${{ needs.coverage-analysis.result }}" == "success" ]]; then
          echo "## 🎉 全テスト成功！" >> $GITHUB_STEP_SUMMARY
          echo "すべてのテストが成功しました。本番デプロイの準備ができています。" >> $GITHUB_STEP_SUMMARY
        else
          echo "## ⚠️ テスト失敗があります" >> $GITHUB_STEP_SUMMARY
          echo "失敗したテストを確認して修正してください。" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**実行時刻**: $(date)" >> $GITHUB_STEP_SUMMARY
        echo "**ブランチ**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "**トリガー**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY